"""LLM-agent simulation of ECB Governing Council rate decisions.

Pipeline per meeting:

1. Each member reads their briefing memo (``data/processed/memos/``) and makes
   an initial position statement (motivation first, then decision).
2. Jev (via the Vercel AI Gateway) extracts each member's position
   (raise/hold/lower), the full probability distribution over the three
   options, and a conviction score — one parallel request per member.
3. The council holds a discussion (>= 2 rounds; every member speaks in every
   round, seeing the full transcript so far). Statements are generated by a
   configurable OpenAI-compatible generator backend.
4. Each member produces a final statement accounting for the discussion; Jev
   extracts position + probabilities + conviction again.

Comparing pre- vs post-discussion extractions yields position flips, confidence
shifts per member profile, and consensus levels per meeting.
"""

from synthetic_council.simulation.agent import Agent, load_agents
from synthetic_council.simulation.config import SimulationConfig
from synthetic_council.simulation.discussion import DiscussionTurn, run_discussion
from synthetic_council.simulation.extraction import (
    PositionExtraction,
    extract_position,
    extract_positions,
)
from synthetic_council.simulation.generator import BaseGenerator, build_generator
from synthetic_council.simulation.runner import run_meeting, run_simulation

__all__ = [
    "SimulationConfig",
    "BaseGenerator",
    "build_generator",
    "PositionExtraction",
    "extract_position",
    "extract_positions",
    "Agent",
    "load_agents",
    "DiscussionTurn",
    "run_discussion",
    "run_meeting",
    "run_simulation",
]
